autobackup/auto_backup_control.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-504
Short description: add success message when using list action in order to sending the list to the front
=> PAAS-504 add success message when action is 'list' (for front)

autobackup/app.py, autobackup/auto_backup_control.yml, autobackup/import_package_as_user.py
JIRA issue: https://jira.jahia.org/browse/PAAS-501
remove region parameter from auto_backup_control.yml
=> PAAS-501: remove region parameter from auto_backup_control.yml

autobackup/app.py
JIRA issue: https://jira.jahia.org/browse/PAAS-505
format auto-backup-control output
=> PAAS-505: format auto-backup-control output

autobackup/app.py
JIRA issue: https://jira.jahia.org/browse/PAAS-505
remove command from listcronjobs output
=> PAAS-505: remove command from listcronjobs output

backup.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-XXX
Nothing particular
=> PAAS-555: fixing missing sudo

backup.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-607
Have to move tag v1.2 to it after merge
=> PAAS-607 add galera has possible value for DB_ENDPOINT

backrest.py
JIRA issue: https://jira.jahia.org/browse/PAAS-635
Fix azure backups
=> PAAS-635: fix azure backup

autobackup/auto_backup.yml, autobackup/auto_backup_control.yml, backup.yml, listbackup.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-651
remove baseurl
Autobackup packages havn't been tested as they are not used anymore
=> Paas 651 remove baseurl

backup.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-722
Accept forms:
1. https://github.com/Jahia/paas_jelastic_backup/raw/master/
2. https://raw.githubusercontent.com/Jahia/paas_jelastic_backup/master/
(old script worked only with 2d form)
=> PAAS-722 update js script to works with the 2 kinds of github urls

backrest.py
JIRA issue: https://jira.jahia.org/browse/PAAS-740
Set container name to lowercases for azure auto backup
=> PAAS-740: Set container name to lowercases for azure auto backup

autobackup/dd_backup.py
JIRA issue: https://jira.jahia.org/browse/PAAS-739
=> PAAS-739 grab email and envname better

backrest.py, backup.yml, listbackup.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-682
remove azure credentials after use
=> PAAS-682: remove azure credentials after use

listbackup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-760
=> Paas 760 - pip install doesn't work

backup.yml, listbackup.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-682
=> Paas 682 use env var instead of credential file for aws

autobackup/auto_backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-739
=> PAAS-739 Use autobackup image v1.3

backup.yml, mixins/common-backup-actions.yml, mixins/elasticsearch.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-878
=> Paas 878 add comments for front

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-932
=> PAAS-932: remove bash comment in javascript for unomi restore

restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-937
Short description: Ronan and I are moles
=> PAAS-937 fix missing pipe for cmd

JahiaCloud/Azure.py
JIRA issue: https://jira.jahia.org/browse/PAAS-946
=> PAAS-946: fix azure backup count used for retention.

mixins/common-backup-actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-964
=> PAAS-964: fixing azure (python library) version

restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-931
=> PAAS-931: purge old index and workspace at jahia restore.

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1054
=> Paas 1054 fix jcustomer151 backup

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1054
=> PAAS-1054: secure ES version retrieval

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1054
=> PAAS-1054: fix restore KO on AWS

README.md
JIRA issue: https://jira.jahia.org/browse/PAAS-1025
=> PAAS-1025: add readme

JahiaCloud/Azure.py, JahiaCloud/aws.py, backrest.py, backup.yml, elasticsearch.py, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-234
=> Paas 234 handle some errors

backup.yml, mixins/elasticsearch.yml, mixins/haproxy.yml, restore.yml
=> Paas 1088 backup haproxy

backup.yml, mixins/haproxy.yml, restore.yml
=> PAAS-1088: handle backward compatibility

restore.yml
=> PAAS-1088: add fix for version < 1.9

backrest.py, backup.yml, mixins/haproxy.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-234
=> PAAS-234: Improve errors management in backrest

mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1133
=> PAAS-1133: Fix azure plugin setup for elasticsearch 7

mixins/haproxy.yml
=> PAAS-1088: fix haproxy backup

restore.yml
=> PAAS-1088: fix env var restore

mixins/haproxy.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1123
=> PAAS-1123: update proc node id after haproxy config restore

backup.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-234
=> PAAS-234: reorder steps to keep a logical progression

mixins/elasticsearch.yml
nodes cluster
JIRA issue: https://jira.jahia.org/browse/PAAS-1133
=> PAAS-1133: fix azure plugin configuration in case of multiple

restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1144
=> Paas 1144 remove envlink

backrest.py
JIRA issue: https://jira.jahia.org/browse/PAAS-1199
=> PAAS-1199: handle OVH region

elasticsearch.py, mixins/elasticsearch.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1199
=> Paas 1199 handle ovh region for es

backup.yml, mixins/common-backup-actions.yml, mixins/elasticsearch.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1237
=> PAAS-1237: improve logs

backup.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1273
=> PAAS-1273: ignore 'file changed as we read it' tar error

restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1271
=> PAAS-1271: handle jahia_cfg_healthcheck_token env var at restore

mixins/haproxy.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1286
=> PAAS-1286: fix processing id restore in haproxy configuration.

backup.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1209
=> PAAS-1209: backup/restore Strongswan conf if present

backup.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1209
=> PAAS-1209: remove strongswan confs from backup/restore

mixins/jcustomer.yml, restore.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1198
=> PAAS-1198: wait env to be ready after a restore

mixins/database.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1507
=> PAAS-1507: fix datadog user password after DB restore
